### ISSUE TITLE
Docker Container

### ISSUE THREAD

**Issue by unclesamwk** [nleng/django-monit-collector#1]
Hey,

i will create a docker container for your very nice monit collector.
In your howto i miss they easy way for a django installation and add your monit collector.
Can you tell it in your README? Thank you ...

greetings Sam

**Comment by nleng** [comment]
Hi, 
thank you for the interest in this project. Sorry, but I don't really understand what you want me to do (Maybe because I never used Docker). 
Best,
Nicor

**Comment by unclesamwk** [comment]
I've newer used django successfully. I need a simple step by step howto to install django and configure your monit-collector within django. Then i built the docker container and everyone can use it in a minute without a big installation with ssl etc ...

**Comment by nleng** [comment]
Ah ok. The problem is, I can't include a complete django tutorial into the REAMDE. There are many different ways how you can setup django depending on your preferences. For example, one should first install a virtual environment so you can host multiple projects each having its own python environment. I use virtualenvwrapper for this. But you can also just install django directly in the main environment (install [pip](https://pip.pypa.io/en/stable/installing/) if not already done):

pip install django
Then make a new project:
django-admin startproject yourProjectName

And then you should be able to start with the REAMDE instructions. But if you want to make it accessible on the web you also need a websever like nginx together with gunicorn. 
For tests you can also just run:
python manage.py runserver 8080
then it should be visible on port 8080.  

Here is a tutorial for django setup very similar to the one I use:
https://www.digitalocean.com/community/tutorials/how-to-set-up-django-with-postgres-nginx-and-gunicorn-on-ubuntu-16-04

**Comment by unclesamwk** [comment]
Thank you, i created a dockercontainer but now wothout gunicorn. Login work, need gunicorn for collect?

**Comment by nleng** [comment]
Usually, when you create the database
`python manage.py syncdb`
you are asked to create a superuser. But you can also do
`python manage.py createsuperuser`

**Comment by unclesamwk** [comment]
Ich merke, Du wohnst in Deutschland, dann ist es einfacher mit der Kommunikation in Deutch. Das mit dem User habe ich bereits hinbekommen. Da ich ALPINE Linux gibt es manchmal ein paar Schwierigkeiten mit python Modulen, etc. Was macht das gunicorn, braucht man das zwingend? Die Weboberfläche funzt auf jedenfall schon ...

**Comment by nleng** [comment]
Also normalerweise macht gunicorn das, was "python manage.py runserver" auch macht, es macht die App von einem Port aus erreichbar (allerdings deutlich effizienter, wenn viele User drauf zugreifen). Nginx holt sich dann von diesem Port die Daten, habe wieder vergessen ob es bei Apache genauso ist. Wenn "die Weboberfläche schon funzt" scheinst du es ja schon irgendwie gelöst zu haben. 
Habe bisher hauptsächlich auf Debian/Ubuntu gearbeitet, deshalb kann ich dir zu deiner Distro nicht viel sagen.
